# Title         : apache_passwords.yml
# Description   : Configure Apache passwords
# Author        : Veltys
# Date          : 2023-08-10
# Version       : 1.0.0
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Ensure passwords file exists'
  ansible.builtin.file:
    path: "/var/www/vhosts/{{ host.apache.sites[i].site }}/passwords"
    state: 'touch'

- name: 'Setting configured sites passwords'
  ansible.builtin.include_tasks: apache_passwords.yml
  loop: "{{ outer_item }}"
  loop_control:
    label: "{{ item.user }}"
  vars:
    j: "{{ i }}"
