# Title         : apache_passwords.yml
# Description   : Configure Apache passwords
# Author        : Veltys
# Date          : 2024-06-19
# Version       : 1.0.1
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Testing if user exists'
  tags:
    - configuration
    - apache
  failed_when: False
  changed_when: found.stderr[-9:] == 'not found'
  ansible.builtin.command:
    cmd: "htpasswd -bv /var/www/vhosts/{{ host.apache.sites[j].site }}/passwords {{ item.user }} {{ item.password }}"
  register: found

- name: 'Calculating configured site user password'
  tags:
    - configuration
    - apache
  ansible.builtin.command:
    cmd: "htpasswd -bmn {{ item.user }} {{ item.password }}"
  register: password
  when: found.stderr[-9:] == 'not found'

- name: 'Setting configured site user security'
  tags:
    - configuration
    - apache
  ansible.builtin.lineinfile:
    create: True
    line: "{{ password.stdout }}"
    path: "/var/www/vhosts/{{ host.apache.sites[j].site }}/passwords"
  when: found.stderr[-9:] == 'not found'
