# Title         : apache.yml
# Description   : Configure Apache
# Author        : Veltys
# Date          : 2023-08-14
# Version       : 1.0.0
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Enable required modules'
  community.general.apache2_module:
    name: "{{ item }}"
    state: 'present'
  loop: "{{ host.apache.modules }}"

- name: 'Copy required templates'
  ansible.builtin.template:
    src: 'apache/000-site.conf.j2'
    dest: "/etc/apache2/sites-available/{{ '%03d' | format(i + 1) }}-{{ item.site }}.conf"
    mode: '666'
  loop: "{{ host.apache.sites }}"
  loop_control:
    index_var: i
    label: "{{ '%03d' | format(i + 1) }}-{{ item.site }}.conf"

- name: 'Remove default site link'
  ignore_errors: True
  ansible.builtin.file:
    path: '/etc/apache2/sites-enabled/000-default.conf'
    state: absent

- name: 'Enable configured sites'
  ansible.builtin.file:
    dest: "/etc/apache2/sites-enabled/{{ '%03d' | format(i + 1) }}-{{ item.site }}.conf"
    src: "../sites-available/{{ '%03d' | format(i + 1) }}-{{ item.site }}.conf"
    state: 'link'
  loop: "{{ host.apache.sites }}"
  loop_control:
    index_var: i
    label: "{{ '%03d' | format(i + 1) }}-{{ item.site }}"

- name: 'Creating configured sites directories'
  ansible.builtin.file:
    path: "/var/www/vhosts/{{ item.site }}/httpdocs"
    state: 'directory'
  loop: "{{ host.apache.sites }}"
  loop_control:
    label: "/var/www/vhosts/{{ item.site }}/httpdocs"

- name: 'Setting configured sites passwords'
  ansible.builtin.include_tasks: apache_loop.yml
  loop: "{{ host.apache.credentials }}"
  loop_control:
    index_var: i
    label: "{{ host.apache.sites[i].site }}"
    loop_var: outer_item

- name: 'Testing new configuration'
  ignore_errors: True
  ansible.builtin.command:
    cmd: 'apachectl configtest'
  register: test_status

- name: 'Restarting Apache 2 service'
  ansible.builtin.systemd_service:
    name: 'apache2'
    state: 'restarted'
  when: not test_status.failed
