# Title         : backup.yml
# Description   : Configure backups
# Author        : Veltys
# Date          : 2023-05-19
# Version       : 1.1.3
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Copy required files'
  tags:
    - configuration
    - backup
  ansible.builtin.copy:
    src: "backup/{{ item.src }}.sh"
    dest: "{{ item.dest }}/{{ item.src }}.sh"
    mode: "{{ item.mode }}"
  loop: "{{ backup.scripts }}"

- name: 'Copy required templates'
  tags:
    - configuration
    - backup
  ansible.builtin.template:
    src: "backup/{{ item.src }}.j2"
    dest: "{{ item.dest }}/{{ item.src }}"
    mode: "{{ item.mode }}"
  loop: "{{ backup.templates }}"

- name: 'Installing crontabs'
  tags:
    - configuration
    - backup
  ansible.builtin.cron:
    job: "{{ item.job }}"
    name: "{{ item.name }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    special_time: "{{ item.special_time | default(omit) }}"
  loop: "{{ backup.crontab_entries }}"
