# Title         : certbot.yml
# Description   : Configure certbot
# Author        : Veltys
# Date          : 2024-09-07
# Version       : 1.2.0
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Copy required files'
  tags:
    - configuration
    - certbot
  ansible.builtin.copy:
    src: "certbot/{{ item.src }}"
    dest: "{{ item.dest }}/{{ item.src }}"
    mode: "{{ item.mode }}"
  loop: "{{ certbot.files }}"

- name: 'Check certificate existence'
  tags:
    - configuration
    - certbot
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ item.site }}"
  register: cert_exists
  loop: "{{ host.apache.sites }}"
  loop_control:
    label: "/etc/letsencrypt/live/{{ item.site }}"

- name: 'Get a new certificate'
  tags:
    - configuration
    - certbot
  ansible.builtin.command:
    cmd: "certbot certonly --agree-tos -d '{{ item.item.site }}'{% if 'www' in host.apache.sites[i].types %} -d 'www.{{ item.item.site }}'{% endif %} --dns-ovh --dns-ovh-credentials /root/.ovh.ini -m servermaster@veltys.es -n"
  when:
    not item.stat.exists or 
    not item.stat.isdir
  loop: "{{ cert_exists.results }}"
  loop_control:
    index_var: i
    label: "{{ item.invocation.module_args.path }}"
