# Title         : crontab.yml
# Description   : Configure crontab
# Author        : Veltys
# Date          : 2023-03-22
# Version       : 1.0.0
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Installing general crontabs'
  ansible.builtin.cron:
    job: "{{ item.job }}"
    name: "{{ item.name }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    special_time: "{{ item.special_time | default(omit) }}"
  loop: "{{ common.crontab.crontab_entries + group.crontab.crontab_entries + host.crontab.crontab_entries }}"
