# Title         : dynamic_dns.yml
# Description   : Configures the Dynamic DNS
# Author        : Veltys
# Date          : 2024-01-22
# Version       : 1.2.0
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Copy required templates'
  ansible.builtin.template:
    src: "dynamic_dns/{{ item.src }}.j2"
    dest: "{{ item.dest }}/{{ item.src }}"
    mode: "{{ item.mode }}"
  loop: "{{ dynamic_dns.templates }}"

- name: 'Execute scripts for the first time'
  ansible.builtin.command:
    cmd: "{{ item.dest }}/{{ item.src }}"
  when: item.src[-3:] == '.sh'
  loop: "{{ dynamic_dns.templates }}"
  loop_control:
    label: "{{ item.src }}"

- name: 'Installing crontabs'
  ansible.builtin.cron:
    job: "{{ item.job }}"
    name: "{{ item.name }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    special_time: "{{ item.special_time | default(omit) }}"
  loop: "{{ dynamic_dns.crontab_entries }}"
