# Title         : ntp.yml
# Description   : Configures the UFW firewall
# Author        : Veltys
# Date          : 2024-05-19
# Version       : 1.0.4
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Common UFW rules configurer'
  tags:
    - configuration
    - firewall
  community.general.ufw:
    comment: "{{ item.comment }}"
    from_ip: "{{ item.src }}"
    proto: "{{ item.proto }}"
    rule: 'allow'
    to_ip: "{{ item.dest }}"
    to_port: "{{ item.port }}"
  loop: "{{ common.ufw.rules }}"

- name: 'Group-specific UFW rules configurer'
  tags:
    - configuration
    - firewall
  community.general.ufw:
    comment: "{{ item.comment }}"
    from_ip: "{{ item.src }}"
    proto: "{{ item.proto }}"
    rule: 'allow'
    to_ip: "{{ item.dest }}"
    to_port: "{{ item.port }}"
  loop: "{{ group.ufw.rules }}"

- name: 'Host-specific UFW rules configurer'
  tags:
    - configuration
    - firewall
  community.general.ufw:
    comment: "{{ item.comment }}"
    from_ip: "{{ item.src }}"
    proto: "{{ item.proto }}"
    rule: 'allow'
    to_ip: "{{ item.dest }}"
    to_port: "{{ item.port }}"
  loop: "{{ host.ufw.rules }}"

- name: 'UFW enabler'
  tags:
    - configuration
    - firewall
  community.general.ufw:
    policy: 'allow'
