# Title         : ntp.yml
# Description   : Configures the UFW firewall
# Author        : Veltys
# Date          : 2023-04-07
# Version       : 1.0.2
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Common UFW rules configurer'
  community.general.ufw:
    comment: "{{ item.comment }}"
    dest: "{{ item.dest }}"
    rule: 'allow'
    src: "{{ item.src }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ common.ufw.rules }}"

- name: 'Group-specific UFW rules configurer'
  community.general.ufw:
    comment: "{{ item.comment }}"
    dest: "{{ item.dest }}"
    rule: 'allow'
    src: "{{ item.src }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ group.ufw.rules }}"

- name: 'Host-specific UFW rules configurer'
  community.general.ufw:
    comment: "{{ item.comment }}"
    dest: "{{ item.dest }}"
    rule: 'allow'
    src: "{{ item.src }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ host.ufw.rules }}"

- name: 'UFW enabler'
  community.general.ufw:
    policy: 'allow'
