# Title         : fstab.yml
# Description   : Configure fstab
# Author        : Veltys
# Date          : 2024-09-07
# Version       : 1.3.2
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Copy required templates'
  no_log: True																	# Password hidden, please!
  ansible.builtin.template:
    src: 'fstab/smbcredentials.j2'
    dest: "/root/.smbcredentials_{{ item.user }}"
    mode: '0600'
  loop: "{{ common.fstab.cifs + group.fstab.cifs + host.fstab.cifs }}"

- name: 'fstab configurer for CIFS mounts'
  block:

  - name: 'Comment in fstab for CIFS mounts'
    lineinfile:
      insertbefore: 'EOF'
      line: '# CIFS mounted folders'
      path: '/etc/fstab'

  - name: 'Entries in fstab for CIFS mounts'
    ansible.posix.mount:
      src: "//{{ item.0.addr }}/{{ item.1.name }}"
      path: "{{ item.1.dest }}"
      fstype: 'cifs'
      opts: "credentials=/root/.smbcredentials_{{ item.0.user }},iocharset=utf8,nofail,file_mode=0777,dir_mode=0777,vers=3.0,x-systemd.automount"
      dump: '0'
      passno: '0'
      state: 'mounted'
    loop: "{{ common.fstab.cifs | subelements('folders') + group.fstab.cifs | subelements('folders') + host.fstab.cifs | subelements('folders') }}"
    loop_control:
      label: "{{ item.1.name }}"

  when: "'cifs-utils' in distro_packages_to_install"

- name: 'fstab configurer for SSHFS mounts'
  block:

  - name: 'Comment in fstab for SSHFS mounts'
    lineinfile:
      insertbefore: 'EOF'
      line: '# SSHFS mounted folders'
      path: '/etc/fstab'

  - name: 'Caculate key hash for SSHFS mounts'
    changed_when: False
    check_mode: False
    delegate_to: localhost
    run_once: True
    ansible.builtin.shell:
#     cmd: "echo -n '[{{ item.addr }}]:{{ item.port }}' | openssl sha1 -mac HMAC -macopt hexkey:$(echo {{ item.ssh_key.salt }} | base64 -d | xxd -p) | awk '{print $2}' | xxd -r -p | base64"
#     cmd: "ssh-keyscan '{{ item.addr }}' | openssl sha1 -mac HMAC -macopt hexkey:$(echo {{ item.ssh_key.salt }} | base64 -d | xxd -p) | awk '{print $2}' | xxd -r -p | base64"
      cmd: "ssh-keyscan '{{ item.addr }}'"
    register: ssh_hashes
    loop: "{{ common.fstab.sshfs + group.fstab.sshfs + host.fstab.sshfs }}"
    loop_control:
      label: "{{ item.addr }}"

  - name: 'Ensure required directory existence'
    ansible.builtin.file:
      path: '/root/.ssh'
      state: 'directory'

  - name: 'Add entries in know_hosts for SSHFS mounts'
    ansible.builtin.include_tasks: fstab_sshfs_known_hosts.yml
    loop: "{{ ssh_hashes.results }}"
    loop_control:
      loop_var: outer_item

  - name: 'Entries in fstab for SSHFS mounts'
    ansible.posix.mount:
      src: "{{ item.0.user }}@{{ item.0.addr }}:{{ item.1.dest }}"
      path: "{{ item.1.dest }}"
      fstype: 'fuse.sshfs'
      opts: "allow_other,IdentityFile={{ ssh_directory }}/id_ed25519"
      dump: '0'
      passno: '0'
      state: 'mounted'
    loop: "{{ common.fstab.sshfs | subelements('folders') + group.fstab.sshfs | subelements('folders') + host.fstab.sshfs | subelements('folders') }}"
    loop_control:
      label: "{{ item.1.name }}"

  when: >
    'fuse-sshfs' in distro_packages_to_install or
    'sshfs' in distro_packages_to_install
