# Title         : fstab_sshfs_known_hosts.yml
# Description   : Configure known_hosts file for sshfs fstab entries
# Author        : Veltys
# Date          : 2024-06-03
# Version       : 1.0.0
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Add entries in know_hosts for SSHFS mounts'
  ansible.builtin.known_hosts:
    path: '/root/.ssh/known_hosts'
    name: "{{ item.split(' ', 1)[0] }}"
    key: "{{ item }}"
  loop: "{{ outer_item.stdout_lines }}"
  loop_control:
    label: "{{ item.split(' ', 1)[0] }}"
