# Title         : ipv6.yml
# Description   : Configure IPv6 support
# Author        : Veltys
# Date          : 2024-05-19
# Version       : 1.0.1
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'IPv6 configurer'
  tags:
    - configuration
    - ipv6
  ansible.builtin.replace:
    path: /etc/sysctl.conf
    regexp: '^net.ipv6.conf.all.disable_ipv6\s*=\s*1'
    replace: 'net.ipv6.conf.all.disable_ipv6 = 0'
