# Title         : mailers.yml
# Description   : Configure mailers
# Author        : Veltys
# Date          : 2024-05-19
# Version       : 1.3.1
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Update git submodule'
  become: False
  delegate_to: localhost
  run_once: True
  tags:
    - configuration
    - mailers
  ansible.builtin.command:
    cmd: 'git submodule update --init'

- name: 'Copy required files'
  tags:
    - configuration
    - mailers
  ansible.builtin.copy:
    src: "mailers/{{ item.src }}"
    dest: "{{ item.dest }}/{{ item.src }}"
    mode: "{{ item.mode }}"
  loop: "{{ mailers.scripts }}"
  when: inventory_hostname in groups['rpis']

- name: 'Copy required templates'
  become: False
  tags:
    - configuration
    - mailers
  ansible.builtin.template:
    src: "mailers/{{ item.src }}.j2"
    dest: "{{ item.dest }}/{{ item.src }}"
    mode: "{{ item.mode }}"
  loop: "{{ mailers.templates }}"

- name: 'Copy root templates'
  tags:
    - configuration
    - mailers
  ansible.builtin.template:
    src: "mailers/{{ item.src }}.j2"
    dest: "{{ item.dest }}/{{ item.src }}"
    mode: "{{ item.mode }}"
  loop: "{{ mailers.templates_root }}"

- name: 'Installing crontabs'
  become: False
  tags:
    - configuration
    - mailers
  ansible.builtin.cron:
    job: "{{ item.job }}"
    name: "{{ item.name }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    special_time: "{{ item.special_time | default(omit) }}"
  loop: "{{ mailers.crontab_entries }}"
