# Title         : motd.yml
# Description   : Configures a fancy MOTD
# Author        : Veltys
# Date          : 2023-06-15
# Version       : 1.0.3
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)
# Notes         : Designed to be executed in a loop


---
- name: 'Copy required files'
  tags:
    - configuration
    - motd
  ansible.builtin.copy:
    src: "MOTD/{{ item }}.sh"
    dest: "/etc/update-motd.d/{{ item }}"
    mode: '0755'
  loop: "{{ motd.files }}"

- name: 'Copy required templates'
  tags:
    - configuration
    - motd
  ansible.builtin.template:
    src: "MOTD/{{ item }}.sh"
    dest: "/etc/update-motd.d/{{ item }}"
    mode: '0755'
  loop: "{{ motd.templates }}"

- name: 'Install required packages'
  tags:
    - configuration
    - motd
  ansible.builtin.package:
    name: "{{ motd.packages }}"
    state: present
  when: motd.packages | length > 0

- name: 'Execute MOTD requirements'
  tags:
    - configuration
    - motd
  ignore_errors: True															# When a one-time operation is required, subsequent operations may fail
  ansible.builtin.command:
    cmd: "{{ item }}"
  loop: "{{ motd.req }}"
