# Title         : ntp.yml
# Description   : Configures the NTP client
# Author        : Veltys
# Date          : 2023-04-28
# Version       : 1.0.1
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'NTP configurer'
  ansible.builtin.lineinfile:
    create: False
    backup: False
    insertbefore: '^pool 0\.[a-z]*\.pool\.ntp\.org iburst$'
    line: "server {{ item }}"
    path: "{{ ntp.file }}"
    state: present
  loop: "{{ ntp.servers }}"
