# Title         : ntp.yml
# Description   : Configures the NTP client
# Author        : Veltys
# Date          : 2024-09-07
# Version       : 2.0.1
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Gather service facts'
  ansible.builtin.service_facts:

- name: 'NTP service configurer'
  tags:
    - configuration
    - ntp
  ansible.builtin.lineinfile:
    create: False
    backup: False
    insertbefore: '^pool 0\.[a-z]*\.pool\.ntp\.org iburst$'
    line: "server {{ item }}"
    path: "{{ ntp.files[0] }}"
    state: 'present'
  loop: "{{ ntp.servers }}"
  when: >
    'ntp' in services and
    services['ntp'].state == 'running'

- name: '''systemd-timesyncd'' service configurer'
  tags:
    - configuration
    - ntp
  ansible.builtin.lineinfile:
    backup: False
    create: False
    insertafter: '^\[Time\]$'
    line: "NTP={{ ntp.servers | join(' ') }}"
    path: "{{ ntp.files[1] }}"
    regexp: '^#?NTP='
    state: 'present'
  when: >
    'systemd-timesyncd' in services and
    services['systemd-timesyncd'].state == 'running'
