# Title         : packages_finder_python.yml
# Description   : Find Python packages to be installed
# Author        : Veltys
# Date          : 2024-08-28
# Version       : 1.0.2
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Clean previous variable states'
  ansible.builtin.set_fact:
    packages_to_install: []

- name: 'Common packages finder'
  tags:
    - configuration
    - packages_finder
  ansible.builtin.set_fact:
    packages_to_install: "{{ packages_to_install | default([]) + common.packages_to_install.python | default([]) }}"

- name: 'Group packages finder'
  tags:
    - configuration
    - packages_finder
  ansible.builtin.set_fact:
    packages_to_install: "{{ packages_to_install + group.packages_to_install.python | default([]) }}"

- name: 'Host packages finder'
  tags:
    - configuration
    - packages_finder
  ansible.builtin.set_fact:
    packages_to_install: "{{ packages_to_install + host.packages_to_install.python | default([]) }}"

- name: 'Save current state'
  ansible.builtin.set_fact:
    python_packages_to_install: "{{ packages_to_install | unique }}"
