# Title         : packages_finder_loop.yml
# Description   : Loop to find packages to be installed
# Author        : Veltys
# Date          : 2024-05-19
# Version       : 1.0.2
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Find required packages'
  tags:
    - configuration
    - installation
    - packages_finder
    - packages
    - python
    - snap
    - ntp
    - firewall
    - backup
    - mailers
    - apache
    - kde
  ansible.builtin.set_fact:
    packages_to_install: "{{ packages_to_install | default([]) + outer_item.packages }}"
  loop: "{{ outer_item.distro }}"
  when: item in ansible_facts['distribution'] | lower
