# Title         : passport.yml
# Description   : Configures the Passport system
# Author        : Veltys
# Date          : 2025-05-05
# Version       : 1.2.0
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- block:
  - name: 'Get iptables binary path'
    tags:
      - configuration
      - passport
    changed_when: false
    check_mode: false
    register: iptables_path_result
    ansible.builtin.command:
      cmd: 'command -v iptables'

  rescue:
    - name: 'Get iptables binary path'
      tags:
        - configuration
        - passport
      changed_when: false
      check_mode: false
      register: iptables_path_result
      ansible.builtin.command:
        cmd: 'which iptables'

- name: 'Set iptables_path from result'
  tags:
    - configuration
    - passport
  set_fact:
    iptables_path: "{{ iptables_path_result }}"

- name: 'Copy required templates'
  tags:
    - configuration
    - passport
  ansible.builtin.template:
    comment_end_string: '#]'
    comment_start_string: '[#'
    src: "passport/{{ item.src }}.j2"
    dest: "{{ item.dest }}/{{ item.src }}"
    mode: "{{ item.mode }}"
  loop: "{{ passport.templates }}"

- name: 'Installing crontabs'
  tags:
    - configuration
    - passport
  ansible.builtin.cron:
    job: "{{ item.job }}"
    name: "{{ item.name }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    special_time: "{{ item.special_time | default(omit) }}"
  loop: "{{ passport.crontab_entries }}"
