# Title         : passport.yml
# Description   : Configures the Passport system
# Author        : Veltys
# Date          : 2024-10-10
# Version       : 1.1.0
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Copy required files'
  tags:
    - configuration
    - passport
  ansible.builtin.copy:
    src: "passport/{{ item.src }}"
    dest: "{{ item.dest }}/{{ item.src }}"
    mode: "{{ item.mode }}"
  loop: "{{ passport.files }}"

- name: 'Installing crontabs'
  tags:
    - configuration
    - passport
  ansible.builtin.cron:
    job: "{{ item.job }}"
    name: "{{ item.name }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    special_time: "{{ item.special_time | default(omit) }}"
  loop: "{{ passport.crontab_entries }}"
