# Title         : passwords.yml
# Description   : Changes the passwords for current and root users
# Author        : Veltys
# Date          : 2023-04-28
# Version       : 1.0.3
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Password changer for current user'
  become: True
  user:
    name: "{{ ansible_user_id }}"
    update_password: always
    password: "{{ host.passwords.password | password_hash('sha512') }}"

- name: 'Password changer for root user'
  become: True
  user:
    name: 'root'
    update_password: always
    password: "{{ host.passwords.password | password_hash('sha512') }}"
