#!/usr/bin/env -S ansible-playbook

# Title         : installer.yml
# Description   : Semi-automated playbook for Installation / configuration of Linux machines
# Author        : Veltys
# Date          : 2023-10-19
# Version       : 1.0.1
# Usage         : ansible-playbook installer.yml | sh installer.yml | bash installer.yml | ./installer.yml
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Installer'
  become: True
  hosts: 'all:!windows'

  roles:
    - installer
