#!/usr/bin/env -S ansible-playbook

# Title         : replicator_clone.yml
# Description   : Playbook to start the Replicator role in clone mode
# Author        : Veltys
# Date          : 2023-02-23
# Version       : 1.0.0
# Usage         : ansible-playbook replicator_clone.yml | sh replicator_clone.yml | bash replicator_clone.yml | ./replicator_clone.yml
# Notes         : It is necessary to be super user for it to work correctly, and also it is necessary to become it (become, do you get it?)


---
- name: 'Ensure root user'
  gather_facts: false
  hosts: localhost
  tags:
    - clean
    - cloner
    - deploy
    - files
    - compress
    - transfer
    - uncompress
    - updater
  tasks:
    - name: 'Check who am I'
      run_once: true
      register: whoami
      ansible.builtin.shell:
        cmd: 'whoami'

    - name: 'Fail if I am not www-data or root'
      run_once: true
      ansible.builtin.fail:
        msg: >
          This script must be run as www-data or root user
          Current user is {{ whoami.stdout }}
          Please use sudo -u www-data ansible-playbook replicator_clone.yml or a similar way to run this playbook
      when: whoami.stdout != 'root' and whoami.stdout != 'www-data'


- name: 'Global vars definition'
  gather_facts: false
  hosts: iuppiter
  tags:
    - clean
    - cloner
    - deploy
    - files
    - compress
    - transfer
    - uncompress
    - updater
  tasks:
    - name: 'Setting environment'
      ansible.builtin.set_fact:
        client: "{{ client }}"
  vars_prompt:
    - name: client
      prompt: 'Please, specify which client should be clonned'
      private: false


- name: 'Replicator in clone to test env mode'
  hosts: iuppiter

  roles:
  - role: replicator
    vars:
      client: client
      mode: 'clone'
