#!/usr/bin/env ansible-playbook

# Title         : test.yml
# Description   : Basic Ansible ping test
# Author        : Veltys
# Date          : 2023-10-19
# Version       : 2.0.0
# Usage         : ansible-playbook test.yml | sh test.yml | bash test.yml | ./test.yml
# Notes         : 


---
- name: 'Test GNU/Linux servers'
  hosts: 'all:!windows'
  gather_facts: no

  tasks:
  - name: 'Ping'
    ansible.builtin.ping:

- name: 'Test Microsoft Windows servers'
  hosts: 'windows'
  gather_facts: no

  tasks:
  - name: 'Ping'
    ansible.builtin.win_ping:
