#!/usr/bin/env ansible-playbook

# Title         : updater.yml
# Description   : Updates the inventory servers thanks to apt or another equivalent module, as well as other independent programs
# Author        : Veltys
# Date          : 2023-02-18
# Version       : 3.0.0
# Usage         : ansible-playbook updater.yml | sh updater.yml | bash updater.yml | ./updater.yml
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Updater'
  hosts: all

  roles:
    - updater
