# Title         : main.yml
# Description   : Confirm facilities main role file
# Author        : rafael.mendez
# Date          : 2023-02-21
# Version       : 1.0.0
# Usage         : (imported as a role by those playbooks which need it)
# Notes         : 


---
- ansible.builtin.include_vars: vars/global.yml

- name: 'Copy required files'
  become: true
  ansible.builtin.copy:
    src: "../files/{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  loop: "{{ files }}"

- name: 'Confirmation by aliases'
  become: true
  ansible.builtin.lineinfile:
    path: "{{ general_aliases_file }}"
    state: present
    create: true
    line: "{{ item }}"
  loop: "{{ general_aliases }}"
