# Title         : general.yml
# Description   : Install required packages
# Author        : Veltys
# Date          : 2023-03-14
# Version       : 1.0.3
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Common packages installer'
  ansible.builtin.package:
    name: "{{ common.packages_to_install }}"
    state: present

- name: 'Group-specific packages installer'
  ansible.builtin.package:
    name: "{{ group.packages_to_install }}"
    state: present

- name: 'Host-specific packages installer'
  ansible.builtin.package:
    name: "{{ host.packages_to_install }}"
    state: present
