# Title         : kde.yml
# Description   : Install KDE
# Author        : Veltys
# Date          : 2024-07-04
# Version       : 1.2.0
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Clean previous variable states'
  tags:
    - installation
    - kde
  ansible.builtin.set_fact:
    packages_to_install: []

- name: 'Find required packages'
  tags:
    - installation
    - kde
  ansible.builtin.include_tasks: '../configurers/packages_finder_loop.yml'
  loop: "{{ kde.packages }}"
  loop_control:
    index_var: i
    label: "{{ kde.packages[i].distro }}"
    loop_var: outer_item

- name: 'Debian-based installer'
  tags:
    - installation
    - kde
  ansible.builtin.package:
    name: "{{ packages_to_install }}"
    state: 'present'
