# Title         : kde.yml
# Description   : Install KDE
# Author        : Veltys
# Date          : 2023-10-04
# Version       : 1.1.0
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Clean previous variables'
  ansible.builtin.set_fact:
    packages_to_install: []

- name: 'Find required packages'
  ansible.builtin.include_tasks: ../configurers/packages_finder_loop.yml
  loop: "{{ kde.packages }}"
  loop_control:
    index_var: i
    label: "{{ kde.packages[i].distro }}"
    loop_var: outer_item

- name: 'Debian-based installer'
  ansible.builtin.package:
    name: "{{ packages_to_install }}"
    state: 'present'
  when: "
    'debian' in ansible_facts['distribution'] | lower() or
    'ubuntu' in ansible_facts['distribution'] | lower()
    "

- name: 'Centos installer'
  ansible.builtin.dnf:
    name: "{{ packages_to_install }}"
    state: 'present'
  when: "
    'centos' in ansible_facts['distribution'] | lower()
    "

- name: 'SUSE installer'
  community.general.zypper:
    name: "{{ packages_to_install }}"
    type: pattern
  when: "
    'suse' in ansible_facts['distribution'] | lower()
    "
