# Title         : general.yml
# Description   : Install required Python packages
# Author        : Veltys
# Date          : 2023-08-02
# Version       : 1.0.0
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Common packages installer'
  ansible.builtin.pip:
    name: "{{ common.packages_to_install.python }}"
    state: 'present'

- name: 'Group-specific packages installer'
  ansible.builtin.pip:
    name: "{{ group.packages_to_install.python }}"
    state: 'present'

- name: 'Host-specific packages installer'
  ansible.builtin.pip:
    name: "{{ host.packages_to_install.python }}"
    state: 'present'
