# Title         : general.yml
# Description   : Install required Python packages
# Author        : Veltys
# Date          : 2024-07-04
# Version       : 1.2.0
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Python installer'
  block:
  - name: 'Common packages installer'
    tags:
      - installation
      - python
    ansible.builtin.pip:
      name: "{{ python_packages_to_install }}"
      state: 'present'

  rescue:
  - name: 'Manual installing required'
    tags:
      - installation
      - python
    ansible.builtin.debug:
      msg: "It seems the Python installer cannot install automatically the required packages. Please, install them manually: [sudo] pip[3] install [--break-system-packages]' {{ python_packages_to_install }}"
