# Title         : warnings.yml
# Description   : Inform about warnings
# Author        : Veltys
# Date          : 2023-03-22
# Version       : 1.0.0
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Show warnings'
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ common.warnings + group.warnings + host.warnings }}"
