# Title         : main.yml
# Description   : Replicator role main tasks file
# Author        : Veltys
# Date          : 2023-07-25
# Version       : 1.1.0
# Usage         : (imported as a role by those playbooks which need it)
# Notes         : 


---
- name: 'Load vars'
  tags:
    - always

  block:
    - name: 'Load client vars'
      ansible.builtin.include_vars: "vars/{{ client }}.yml"

  rescue:
  - name: 'Inform about the error'
    debug:
      msg: 'Client ''{{ client }}'' supplied is not valid. Please, provide a valid client, cannot continue.'

  - name: 'Stop playbook execution'
    meta: end_play


- name: 'Mode switcher'
  block:
    - ansible.builtin.import_tasks: "{{ mode }}.yml"

  rescue:
  - name: 'Inform about the error'
    debug:
      msg: '''mode'' parameter is requiered but not given or is wrong. Please, provide a valid mode, cannot continue.'

  - name: 'Stop playbook execution'
    meta: end_play
