# Title         : apt.yml
# Description   : Updates the inventory Debian based servers thanks to apt module
# Author        : Veltys
# Date          : 2023-02-18
# Version       : 1.0.1
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Updater and upgrader for Debian based distros'
  become: true
  register: updatesys
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes

- name: 'Display all the lines of the apt task if changed'
  ansible.builtin.debug:
    msg: "{{ updatesys.stdout_lines }}"
  when: updatesys.changed

- name: 'Autoremove no longer required packages'
  become: true
  ansible.builtin.apt:
    autoremove: true
