# Title         : main.yml
# Description   : Updater role main file
# Author        : Veltys
# Date          : 2023-08-01
# Version       : 4.0.1
# Usage         : (imported as a role by those playbooks which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Updater and upgrader'
  tags:
    - update
    - upgrade
  ansible.builtin.package:
    name: '*'
    state: 'latest'
    update_cache: yes
  when: "
    'centos'	in ansible_facts['distribution'] | lower() or
    'debian'	in ansible_facts['distribution'] | lower() or
    'fedora'	in ansible_facts['distribution'] | lower() or
    'red hat'	in ansible_facts['distribution'] | lower() or
    'suse'		in ansible_facts['distribution'] | lower() or
    'ubuntu'	in ansible_facts['distribution'] | lower()
    "

- name: 'Netdata upgrader for systems with no Netdata binary repo'
  tags:
  - netdata
  - upgrade
  ansible.builtin.shell:
    cmd: '/usr/libexec/netdata/netdata-updater.sh'
  when:
    ansible_facts.architecture == 'armv6l' and
    netdata_build | lower() == 'y'

# TODO: Better condition
- name: 'Old ansible updater and upgrader (opkg) for OpenSPA'
  tags:
  - opkg
  - update
  - upgrade

  block:
  - name: 'Old ansible updater (opkg) for OpenSPA'
    ansible.builtin.shell:
      cmd: 'opkg update'

  - name: 'Old ansible upgrader (opkg) for OpenSPA'
    ansible.builtin.shell:
      cmd: 'opkg upgrade'

  when: "
    'centos'	not in ansible_facts['distribution'] | lower() and
    'debian'	not in ansible_facts['distribution'] | lower() and
    'fedora'	not in ansible_facts['distribution'] | lower() and
    'red hat'	not in ansible_facts['distribution'] | lower() and
    'suse'		not in ansible_facts['distribution'] | lower() and
    'ubuntu'	not in ansible_facts['distribution'] | lower()
    "
