# Title         : main.yml
# Description   : Updater role main file
# Author        : Veltys
# Date          : 2024-09-25
# Version       : 4.2.0
# Usage         : (imported as a role by those playbooks which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Updater and upgrader'
  tags:
    - update
    - upgrade
  ansible.builtin.package:
    name: '*'
    state: 'latest'
    update_cache: yes
  when: >
    'centos'	in ansible_facts['distribution'] | lower() or
    'debian'	in ansible_facts['distribution'] | lower() or
    'fedora'	in ansible_facts['distribution'] | lower() or
    'red hat'	in ansible_facts['distribution'] | lower() or
    'suse'		in ansible_facts['distribution'] | lower() or
    'ubuntu'	in ansible_facts['distribution'] | lower()

- name: 'Old updater and upgrader (opkg) for OpenSPA'
  tags:
  - opkg
  - update
  - upgrade

  block:
  - name: 'Old ansible updater (opkg) for OpenSPA'
    ansible.builtin.shell:
      cmd: 'opkg update'

  - name: 'Old ansible upgrader (opkg) for OpenSPA'
    ansible.builtin.shell:
      cmd: 'opkg upgrade'

  when: >
    'openspa'	in ansible_facts['distribution'] | lower() or
    'openpli'	in ansible_facts['distribution'] | lower()

- name: 'Unknown updater and upgrader'
  tags:
  - unknown
  - update
  - upgrade

  block:
  - name: 'Updater and upgrader for unknown systems'
    ansible.builtin.debug:
      msg: "WARNING: Unknown reported system in ansible facts ({{ ansible_facts['distribution'] }}), cannot update and upgrade"

  when: >
    'centos'	not in ansible_facts['distribution'] | lower() and
    'debian'	not in ansible_facts['distribution'] | lower() and
    'fedora'	not in ansible_facts['distribution'] | lower() and
    'red hat'	not in ansible_facts['distribution'] | lower() and
    'suse'		not in ansible_facts['distribution'] | lower() and
    'ubuntu'	not in ansible_facts['distribution'] | lower() and
    'openspa'	not in ansible_facts['distribution'] | lower() and
    'openpli'	not in ansible_facts['distribution'] | lower()
