# Title         : main.yml
# Description   : Updater role main file
# Author        : Veltys
# Date          : 2023-02-18
# Version       : 3.0.0
# Usage         : (imported as a role by those playbooks which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Updater and upgrader for Debian based distros'
  tags:
    - apt
    - update
    - upgrade
  ansible.builtin.import_tasks: apt.yml
  when:
    ansible_facts.distribution == 'Ubuntu' or
    ansible_facts.distribution == 'Debian'

- name: 'Updater and upgrader for Red Hat based distros'
  tags:
    - yum
    - update
    - upgrade
  ansible.builtin.import_tasks: yum.yml
  when:
    ansible_facts.distribution == 'Red Hat' or
    ansible_facts.distribution == 'CentOS'

- name: 'Updater and upgrader for SUSE based distros'
  tags:
    - zypper
    - update
    - upgrade
  ansible.builtin.import_tasks: zypper.yml
  when:
    "'SUSE' in ansible_facts['distribution'] | upper()"

# TODO: More conditions
- name: 'Netdata upgrader for systems with no Netdata binary repo'
  tags:
  - netdata
  - upgrade
  ansible.builtin.import_tasks: netdata.yml
  when: ansible_facts.architecture == 'armv6l'

# TODO: Better condition
- name: 'Old ansible upgrader (opkg) for OpenSPA'
  tags:
  - opkg
  - update
  - upgrade
  ansible.builtin.import_tasks: opkg.yml
  when:
      ansible_facts.distribution != 'Ubuntu' and
      ansible_facts.distribution != 'Debian' and
      ansible_facts.distribution != 'Red Hat' and
      ansible_facts.distribution != 'CentOS' and
      "'SUSE' in ansible_facts['distribution'] | upper()"
