# Title         : yum.yml
# Description   : Updates the inventory Red Hat based servers thanks to yum module
# Author        : Veltys
# Date          : 2023-04-28
# Version       : 1.0.2
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Updater and upgrader for Red Hat based distros'
  become: True
  register: updatesys
  ansible.builtin.yum:
    name: "*"
    state: latest
    update_cache: yes

- name: 'Display all the lines of the yum task if changed'
  ansible.builtin.debug:
    msg: "{{ updatesys.stdout_lines }}"
  when: updatesys.changed

- name: 'Autoremove no longer required packages'
  become: True
  ansible.builtin.yum:
    autoremove: True
