# Title         : zypper.yml
# Description   : Updates the inventory SUSE based servers thanks to zypper module
# Author        : Veltys
# Date          : 2023-04-28
# Version       : 1.0.2
# Usage         : (included as a tasks file by those tasks files which need it)
# Notes         : It is not necessary to be super user for it to work correctly, but it is necessary to become it (become, do you get it?)


---
- name: 'Updater and upgrader for SUSE based distros'
  become: True
  register: updatesys
  community.general.zypper:
    name: "*"
    state: latest
    update_cache: yes

- name: 'Display all the lines of the zypper task if changed'
  ansible.builtin.debug:
    msg: "{{ updatesys.stdout_lines }}"
  when: updatesys.changed

# TODO: Not implemented yet
# become: True
# - name: 'Autoremove no longer required packages'
#   community.general.zypper:
#     autoremove: True
